a:7:{s:4:"name";s:13:"Fathi Al Sadi";s:5:"email";s:18:"Lastsone@gmail.com";s:7:"toEmail";s:23:"fathii.alsadi@gmail.com";s:7:"subject";s:46:"New contact form submission from Fathi Al Sadi";s:4:"body";s:392:"
            <h1>New message</h1>
            <p><strong>Name:</strong> Fathi Al Sadi</p>
            <p><strong>Email:</strong> Lastsone@gmail.com</p>
            <p><strong>Phone:</strong> 0797915775</p>
            <p><strong>Service:</strong> Marketing</p>
            <p><strong>Message:</strong> asxasxsaxasxasx</p>
            <p><strong>Time:</strong> 2025-05-18 09:15:41</p>
        ";s:7:"altBody";s:107:"Name: Fathi Al Sadi
Email: Lastsone@gmail.com
Phone: 0797915775
Service: Marketing
Message: asxasxsaxasxasx";s:8:"metadata";a:3:{s:5:"phone";s:10:"0797915775";s:7:"service";s:9:"Marketing";s:10:"submitTime";s:19:"2025-05-18 09:15:41";}}